'use strict';
const q=new URLSearchParams(location.search),FALLBACK='2026-08-27',requested=q.get('date')||FALLBACK,AGENDA_DATE=/^2026-(08|09)-\d{2}$/.test(requested)?requested:FALLBACK,CBI_START='2026-09-23';
const dateObj=new Date(AGENDA_DATE+'T12:00:00'),DAY=dateObj.toLocaleDateString('en-US',{weekday:'long'}).toUpperCase(),DATE=dateObj.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}).toUpperCase();
const ALL=['Sophia','Sincere','Hussain','Carter','Roman','Victoria','Brendon','Lewis','Lovell'],students=DAY==='MONDAY'?ALL:ALL.filter(x=>x!=='Sincere'),staff=['Ms. Betsy','Ms. Katie','Mr. Tim'];
const CLOSURES={'2026-09-04':'No School – Friday Before Labor Day','2026-09-07':'No School – Labor Day','2026-09-21':'No School – Yom Kippur'},HALF={'2026-08-24':'First Day of School · AM Only','2026-09-18':'AM Only – Half Day'},weekend=[0,6].includes(dateObj.getDay()),scheduled=CLOSURES[AGENDA_DATE]||(weekend?'Weekend – No School':''),half=!!HALF[AGENDA_DATE];
const DEFAULT_MG='https://app.peardeck.com/student/tnavqgogg',SEPT='September Focus: Visual Schedule & Following Directions';
const A={};let ready=false,current=0,staffMode=false;
function defaultImportant(){if(half)return [HALF[AGENDA_DATE]];if(DAY==='MONDAY')return ['Laundry day'];if(DAY==='TUESDAY'&&AGENDA_DATE>='2026-09-01')return ['Speech with Julie'];if(DAY==='WEDNESDAY'&&AGENDA_DATE>=CBI_START)return ['CBI · 10:00–11:30'];if(DAY==='WEDNESDAY')return ['Drew Life Skills · 12:45–2:00'];if(DAY==='THURSDAY')return ['Shop · 10:00–11:00'];if(DAY==='FRIDAY')return ['Friday group','Laundry after lunch'];return ['Regular full day']}
function defaultMenu(){if(AGENDA_DATE==='2026-08-25')return ['Bosco Bar','Bosco Cheese Sticks','Marinara Dipping Cup','Cucumber Slices'];if(AGENDA_DATE==='2026-08-26')return ['Chicken Basket','Chicken Tenders','Biscuit','Green Beans'];return ["Check today's lunch menu"]}
const defaults={important:defaultImportant(),noSchool:!!scheduled,noSchoolReason:scheduled||'',staffAbsent:[],morningUrl:DEFAULT_MG,musicUrl:'https://www.youtube.com/watch?v=HFlxEM6zZsc',videos:['','',''],lunchMenu:defaultMenu(),checkin:{},participation:{},partNotes:{},impact:{}};
const KEY='room6-agenda-v2-'+AGENDA_DATE;let state;try{state=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){state={...defaults}};for(const k of ['staffAbsent','videos','lunchMenu'])if(!Array.isArray(state[k]))state[k]=defaults[k];for(const k of ['checkin','participation','partNotes','impact'])state[k]=state[k]||{};if(scheduled){state.noSchool=true;state.noSchoolReason=scheduled}
const E={arrival:[['📦','Put your things where they go'],['✅','Check in'],['🍽️','Get breakfast'],['👋','Greetings'],['📅','Check schedule']],checkin:[['👀','Look'],['🖼️','Find your picture'],['☑️','Check the box'],['💬','Use AAC if needed']],group:[['📅','Check Schedule'],['🪑','Sitting'],['🔇','Voice Off'],['✅','Ready to Work']],choice:[['👉','Choose an activity'],['💻','Computer'],['🎨','Draw'],['🚶','Walk'],['💡','What is your idea?']],lunch:[['🍽️','Get lunch'],['🪑','Sit'],['🥪','Eat'],['🧹','Clean up'],['📅','Check schedule'],['🎯','Choose a leisure activity']],station:[['📅','Check Schedule'],['🪑','Sitting'],['🔇','Voice Off'],['✅','Ready to Work']]};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function extractAssets(){try{const d=document.getElementById('assetFrame').contentDocument;if(!d)return false;for(const n of [...ALL,...staff]){const im=[...d.images].find(x=>x.alt===n);if(im)A[n]=im.src}A.arrival=d.querySelector('img[alt="Arrival visual"]')?.src||'';A.lunch=d.querySelector('img[alt="Lunch visual"]')?.src||'';A.morning=d.querySelector('img[alt="Morning Group visual"]')?.src||'';A.stations=d.querySelector('img[alt*="Stations Group 1 visual"]')?.src||'';A.enrich=d.querySelector('img[alt*="Adult doing exercise"]')?.src||'';return !!A.arrival}catch(e){return false}}
const G1=['Hussain','Lewis','Carter'],G2=['Roman','Victoria','Brendon'];
const good=()=>({id:'good',title:'Good Morning!',kind:'good',expect:E.arrival,timer:10}),checkin=()=>({id:'checkin',title:'Check In',kind:'checkin',expect:E.checkin,timer:10}),menu=()=>({id:'menu',title:"What's For Lunch?",kind:'menu',expect:E.lunch,timer:5}),morning=()=>({id:'morning',title:'Morning Group',kind:'morning',expect:E.group,timer:20,note:AGENDA_DATE.startsWith('2026-09')?SEPT:''}),s1=()=>({id:'station1',title:'Stations Group 1',kind:'station',expect:E.station,timer:15,group:G1,break:'Group 2: On Break'}),s2=()=>({id:'station2',title:'Stations Group 2',kind:'station',expect:E.station,timer:15,group:G2,break:'Group 1: On Break'}),choice=(id,next,time='',timer=15)=>({id,title:'Choice Time',kind:'choice',expect:E.choice,timer,next,time}),lunch=()=>({id:'lunch',title:'Lunch',kind:'lunch',expect:E.lunch,timer:30,time:'Lunch 11:45–12:15'}),enrich=()=>({id:'enrich',title:'Enrichments',kind:'enrich',expect:E.group,timer:45,time:'2:00–2:45 PM'}),home=(time='')=>({id:'home',title:'Time to Go Home',kind:'home',timer:10,noExpect:true,time}),task=(id,title,icon,steps,time='',group=[],expect=E.group,timer=20)=>({id,title,kind:'task',icon,steps,time,group,expect,timer});
function build(){if(half)return [good(),checkin(),morning(),choice('choice1','Stations Group 1','Half Day · AM Only'),s1(),s2(),home('Half Day · dismissal 11:45 AM')];const c=[good(),checkin(),menu(),morning()];if(DAY==='MONDAY'){c.splice(2,0,task('laundryAM','Laundry','🧺',['9:05 · Take laundry to the apartment','9:07 · Put laundry in the washer','10:05 · Move laundry to the dryer','10:50 · Bring laundry back to Room 6','10:50–11:15 · Fold and sort laundry'],'Morning laundry',['Carter','Victoria','Roman','Lewis'],E.station));return [...c,choice('choice1','Stations Group 1'),s1(),s2(),choice('choice2','Lunch','Lunch 11:45–12:15'),lunch(),choice('choice3','Enrichments','Next: Enrichments at 2:00 PM',30),enrich(),home()]};if(DAY==='TUESDAY'){const a=[...c],speech=AGENDA_DATE>='2026-09-01';if(speech)a.push(choice('choiceSpeech','Speech with Julie'),task('speech','Speech with Julie','💬',['Check schedule','Go with Julie','Use your voice or AAC','Return to Room 6 when finished'],'',[],E.group,30),choice('choiceLunch','Lunch','Lunch 11:45–12:15'));else a.push(choice('choiceLunch','Lunch','Lunch 11:45–12:15',30));return [...a,lunch(),s1(),s2(),choice('choiceEnrich','Enrichments','Next: Enrichments at 2:00 PM'),enrich(),home()]};if(DAY==='WEDNESDAY'){const a=[...c];if(AGENDA_DATE>=CBI_START)a.push(choice('choiceCBI','CBI','CBI 10:00–11:30'),task('cbi','CBI','🚌',['Check schedule','Bring your own money if you want to buy something','Stay with the group','Return to Room 6'],'10:00–11:30',[],E.group,90));else a.push(choice('choiceLunch','Lunch','Lunch 11:45–12:15',45));return [...a,lunch(),choice('choiceAfterLunch','Stations Group 1','Drew Life Skills · 12:45–2:00',30),s1(),s2(),choice('choiceEnrich','Enrichments','Drew Life Skills · 12:45–2:00'),enrich(),home()]};if(DAY==='THURSDAY')return [...c,task('shop','Shop','🛠️',['Check schedule','Go to Shop','Follow the work steps','Return to Room 6'],'10:00–11:00',[],E.group,60),choice('choiceLunch','Lunch','Lunch 11:45–12:15',30),lunch(),s1(),s2(),choice('choiceEnrich','Enrichments','Next: Enrichments at 2:00 PM'),enrich(),home()];if(DAY==='FRIDAY')return [...c,choice('choiceStations','Stations Group 1'),s1(),s2(),choice('choiceLunch','Lunch','Lunch 11:45–12:15'),lunch(),task('laundryPM','Laundry','🧺',['12:15 · Take laundry to the apartment','12:20 · Put laundry in the washer','1:15 · Move laundry to the dryer','2:00 · Bring laundry back to Room 6','2:05–2:30 · Fold and sort laundry'],'Friday laundry',['Carter','Victoria','Roman','Lewis'],E.station),choice('choiceEnd','End of Day'),home()];return [...c,lunch(),home()]}
const slides=build();
